backend:
  name: github
  repo: kgeraldoq/ags       # your GitHub repo
  branch: main
  auth_type: implicit
  app_id: bKkQmPY311RdYbi5s8zGfQHINGV4B4zz   # your Auth0 Client ID
  base_url: https://dev-kc4fndov4sxpi5cv.us.auth0.com   # your Auth0 domain

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Promotions & News"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }

  - name: "prices"
    label: "Price List"
    folder: "prices"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Material Name", name: "material", widget: "string" }
      - { label: "Price per unit", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Last Updated", name: "date", widget: "datetime" }
